stages:
  - main-pre
  - main

main-pre:
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
  stage: main-pre
  image: python:latest
  script:
    - pwd
    - cd spring-boot-starter-oauth2
    - pwd
    - python merge.py
  artifacts:
    paths:
      - spring-boot-starter-oauth2/src/main/java



main:
  needs:
    - job: main-pre
      artifacts: true
  stage: main
  image: maven:3.6.3-jdk-8
  variables:
    MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
    MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  cache:
    paths:
      - .m2/repository
  script:
    - GPG_FILE=`find / -name xuxiaowei_0x97A36125_SECRET`
    - echo $GPG_FILE
    - gpg --import $GPG_FILE
    - sed -i "s#</servers>#<server><id>ossrh</id><username>$ossrh_user</username><password>$ossrh_pass</password></server>&#" settings.xml
    - git --version
    - pwd
    - cd spring-boot-starter-oauth2
    - pwd
    - NAME=`mvn help:evaluate -Dexpression=project.name -q -DforceStdout -s settings.xml`
    - VERSION=`mvn help:evaluate -Dexpression=project.version -q -DforceStdout -s settings.xml`
    - PACKAGING=`mvn help:evaluate -Dexpression=project.packaging -q -DforceStdout -s settings.xml`
    - echo 名称：$NAME
    - echo 版本：$VERSION
    - echo 包：$PACKAGING
    - echo 常量网址：https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - echo 当前分支：$CI_COMMIT_BRANCH
    - echo 主分支：$CI_DEFAULT_BRANCH
    - echo 项目路径：$CI_PROJECT_DIR
    - mvn clean -U package source:jar javadoc:jar deploy -Pgpg -DskipTests -s settings.xml && echo 发布完成
  artifacts:
    paths:
      - spring-boot-starter-oauth2/target/spring-boot-starter-oauth2-*
