# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        java-version: [ 8, 11, 17 ]
        os: [ "ubuntu-latest" ]

    steps:
      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: maven

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: pre
        run: |
          pwd
          cd spring-boot-starter-oauth2
          pwd
          python merge.py
          ls src/main/java/org/springframework/security/oauth2/server/authorization/http

      - name: Build with Maven
        run: |
          pwd
          cd spring-boot-starter-oauth2
          pwd
          mvn clean -e -U package source:jar javadoc:jar install -DskipTests
